openapi: '3.0.2'
info:
  title: DoorsAPI
  version: '1.0'
paths:
  /info:
    get:
      operationId: getInfo
      tags:
        - "Doors"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
  
  /move:
    post:
      operationId: move
      tags:
        - "Doors"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MoveRequest"

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MoveResponse"
        '400':
          description: "Bad request. A parameter is out of range or missing"
        '412':
          description: "Precondition failed. Move was issued while door was moving"

components:
  schemas:
    InfoResponse:
      properties:
        type:
          type: string
          description: "The type of the device queried. Must be checked to be 'door'"
        max_steps:
          type: integer
          description: "The maximum step position that may be used"
        max_speed:
          type: integer
          description: "The maximum value for speed"
        position_left:
          type: integer
          description: "The current position of the left door"
        position_right:
          type: integer
          description: "The current position of the right door"
        closed_position:
          type: integer
          description: "The position to move to in order to close the doors"
        open_position:
          type: integer
          description: "The position to move to in order to open the doors"
    
    MoveRequest:
      required:
        - "mode"
      properties:
        mode:
          type: string
          description: "One of 'move' and 'learn. For 'move', 'position' is also required to be present"
        position:
          type: integer
          description: "The absolute position to move to"
        speed:
          type: number
          description: "The speed to move at, in stesp per second. Accepts fractional numbers down to 0.001"

    MoveResponse:
      properties:
        result:
          type: string
          description: "The result of the request. Expected to be 'ok'"